title: The Onyx Platform
email: michael.drogalis@onyxplatform.org
description: >
  Distributed, masterless, high performance, fault tolerant data processing
baseurl: ""
url: "http://www.onyxplatform.org"
twitter_username: OnyxPlatform
github_username: onyx-platform

markdown: kramdown

kramdown:
  input: GFM
  coderay_line_numbers: nil

categories: [user-guide-page]

onyx_version: 0.14.x
